export const GET_TECHNICIANS = "GET_TECHNICIANS";
export const ADD_TECHNICIAN = "ADD_TECHNICIAN";
export const DELETE_TECHNICIAN = "DELETE_TECHNICIAN";
export const SET_TECHNICIANS_LOADING = "SET_TECHNICIANS_LOADING";
export const SET_TECHNICIANS_ERROR = "SET_TECHNICIANS_ERROR";
